controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
home:
    path: /
    controller: App\Controller\HomeController::index
app_profile_show:
    path: /profil
    controller: App\Controller\ProfilController::showProfil
app_profile_edit:
    path: /profil/edit
    controller: App\Controller\ProfilController::editProfil



